[SECRET_KEY]
KEY = YOUR_SECRET_KEY

[DATABASE]
ADDRESS = YOUR_MONGODB_ADDRESS

[EMAIL_SENDER]
EMAIL_ADDRESS = YOUR_GMAIL_ADDRESS
EMAIL_PASSWORD = YOUR_GMAIL_APP_PASSWORD
EMAIL_SERVER = smtp.gmail.com
EMAIL_PORT = 587